version: '3'

services:
  mysqldev:
    container_name: mysqldev
    image: "mysql:latest"
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=scheduler
      - MYSQL_USER=sadmin
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
    
  scheduler:
    image: scheduler-image
    container_name: scheduler
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      mysqldev:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: sadmin
      SPRING_DATASOURCE_PASSWORD: password  
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldev:3306/scheduler
    volumes:
      - ./data/spring-boot-app
